# Title left blank on purpose so that the logo is used instead
title: ''
author: The NRSurrogate Catalog Team
logo: logo.png

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: main.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/sxs-collaboration/nrsur_catalog
  branch: gh-pages
  path_to_book: _sources

html:
  favicon: favicon.png
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  show_prev_next: false
  comments:
    utterances:
      repo: "avivajpeyi/nrsur_catalog"




sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  - sphinxcontrib.bibtex
  - sphinx.ext.autodoc
  - sphinxcontrib.youtube
  - sphinxarg.ext
  html_js_files:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex2jax:
        inlineMath: [ [ "$","$" ], [ "\\(", "\\)" ] ]
    myst_update_mathjax: false

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""


