# Title left blank on purpose so that the logo is used instead
title: ''
author: The NRSurrogate Catalog Team
logo: https://raw.githubusercontent.com/nrsur-catalog/logo/main/nrsurcat_1_logo.png
copyright: "2023"

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: main.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/nrsur-catalog/NRSurCat-1
  branch: gh-pages
  path_to_book: _sources

html:
  favicon: https://raw.githubusercontent.com/nrsur-catalog/logo/main/nrsurcat_favicon.png
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  show_prev_next: false
  google_analytics_id: G-CKD8RBPZ5H
  comments:
    utterances:
      repo: "avivajpeyi/nrsur_catalog"


parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  - sphinxcontrib.bibtex
  - sphinx.ext.autodoc
  - sphinxcontrib.youtube
  - sphinxarg.ext
  html_js_files:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex2jax:
        inlineMath: [ [ "$","$" ], [ "\\(", "\\)" ] ]
    myst_update_mathjax: false

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""


