"""Module to upload NRSur Catlog fits to Zenodo
Used just by NRSur Catalog developers/maintainers
"""
import zenodopy
import os
import argparse
from zenodo_get.zget import zenodo_get
from ..logger import logger
from ..utils import get_event_name

HERE = os.path.dirname(os.path.abspath(__file__))
URL_FILE = os.path.join(HERE, "zenodo_urls.txt")  # This file's contents are autogenerated
NRSUR_ZENODO_PROJECT_ID = 1164736


def get_zenodo_project(access_token: str) -> zenodopy.Client:
    """Get the write-access to zenodo project"""
    zeno = zenodopy.Client(token=access_token, sandbox=True)
    zeno.set_project(NRSUR_ZENODO_PROJECT_ID)
    return zeno


def upload_file_to_zenodo(filepath: str, access_token: str) -> None:
    """Upload the NRSur Catlog fits to Zenodo given the fit name"""
    zeno = get_zenodo_project(access_token)
    zeno.upload_file(filepath)
    logger.info(f"Uploaded {filepath} to Zenodo (project {zeno})")


def cache_zenodo_file_urls(url_file: str):
    """Update the file URLs to the data on zenodo"""
    zenodo_get(
        argv=[f"--wget={url_file}", "-s", '-r', NRSUR_ZENODO_PROJECT_ID]
    )


def get_zenodo_urls() -> dict:
    """Returns a dictionary of the analysed fits and their urls"""
    # read in the zenodo_urls.txt file (each line is a url)
    with open(URL_FILE, "r") as f:
        urls = f.readlines()
        urls = [url.strip() for url in urls]

    if len(urls) == 0:
        raise RuntimeError("No URLs found in zenodo_urls.txt")

    # extract the fit name from the url
    fit_names = [get_event_name(url) for url in urls]
    return dict(zip(fit_names, urls))


def main() -> None:
    """Main function to upload the NRSur Catlog fits to Zenodo"""
    parser = argparse.ArgumentParser(
        description="Upload the NRSur Catlog fits to Zenodo"
    )
    parser.add_argument(
        "path",
        type=str,
        help="Path to the fit to upload to Zenodo",
    )
    parser.add_argument(
        "--access_token",
        type=str,
        help="Zenodo access token",
    )
    args = parser.parse_args()
    upload_file_to_zenodo(args.path, args.access_token)
